apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ssv-ss
  namespace: ssv
spec:
  serviceName: ssv-service
  replicas: 1
  selector:
    matchLabels:
      app: ssv
  template:
    metadata:
      labels:
        app: ssv
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
      containers:
      - name: ssv
        image: bloxstaking/ssv-node:latest
        securityContext:
          runAsUser: 0
          runAsGroup: 0
        ports:
        - containerPort: 12000
          name: port-12000
          protocol: UDP
        - containerPort: 13000
          name: port-13000
        - containerPort: 15000
          name: port-15000
        env:
        - name: CONFIG_PATH
          value: /tmp/config.yaml
        command: ["/bin/sh","-c"]
        args: ["make HOST_ADDRESS=<<ssv-load-balancer-external-ip>> start-node;"]
        volumeMounts:
        - name: ssvdata
          mountPath: /opt/ssv/data
        - name: config-volume
          mountPath: /tmp/config.yaml
          subPath: config.yaml
          readOnly: true
      volumes:
      - name: config-volume
        secret:
          secretName: ssv-config
  volumeClaimTemplates:
  - metadata:
      name: ssvdata
      namespace: ssv
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
